### ISSUE TITLE
How do I turn off Dart support?

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#431] opened 2015-10-19 16:47 UTC
Use case: open the sdk directory, fresh from GitHub, in Atom.

I see a ton of errors and feedback. It's not clear how to tell the Dart plugin "you can ignore everything from the sdk directory, on down, as I'm not editing Dart code".

Ideally, the sdk directory itself would be errors and warning free. But assuming that's not possible, I'd like to be able to open the sdk directory with Atom and not spin up the analyzer.

Thanks for any suggestions!

Atom 1.0.19, dartlang 0.4.9, SDK 1.13.0-dev.7.0 running on macos.

**Comment by devoncarew** [comment] 2015-10-19 16:55
One way might be to create an `.analysis_options` file in the root dir, configure it to ignore everything, and then gitignore that file.

**Comment by devoncarew** [comment] 2015-12-11 18:44
Dupe of #609

**Closed by devoncarew** 2015-12-11 18:44 UTC
Labels: question
