### ISSUE TITLE
Would be nice to have in-line type completion

### ISSUE THREAD

**Issue by eseidel** [dart-atom/dartlang#165] opened 2015-08-03 16:38 UTC
```
import 'package:args/args.dart';

void main() {
    Arg[tab] parser = new ArgParser();
}
```

Hit tab where indicated.
Expected: To complete to `ArgParser` (or at least offer completions).
Actual: Tab inserted.

**Comment by sethladd** [comment] 2015-08-03 19:29
Hi Eric,

Have you tried control-space on a mac? Tab doesn't code complete, AFAIK.

![screen shot 2015-08-03 at 12 28 31 pm](https://cloud.githubusercontent.com/assets/5479/9045819/395ff57a-39db-11e5-8730-562a2659c773.png)

**Comment by sethladd** [comment] 2015-09-18 19:37
Closing as "can't reproduce"

**Closed by sethladd** 2015-09-18 19:37 UTC
