### ISSUE TITLE
Running an app with a breakpoint doesn't stop on breakpoint

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#655] opened 2015-12-15 21:30 UTC
I created a sample app and set a breakpoint (with F9), and then I ran my app with Cmd-R.

Expected: app to stop at breakpoint.

Actual: app ran just fine.

![screen shot 2015-12-15 at 1 29 04 pm](https://cloud.githubusercontent.com/assets/5479/11824657/f32e6ed8-a32f-11e5-8edb-6cbf90749028.png)

**Comment by devoncarew** [comment] 2015-12-15 21:42
dupe of https://github.com/dart-atom/dartlang/issues/626?

**Closed by devoncarew** 2015-12-15 21:42 UTC
Labels: bug, debugger
