### ISSUE TITLE
Running a test via Atom doesn't seem to work

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#722] opened 2016-01-26 06:08 UTC
* clone the dartdoc repo
* open in atom
* right-click on test/model_test.dart
* select "Run application"

Expected: test to run, output displayed in console.

Actual:

![screen shot 2016-01-25 at 10 06 55 pm](https://cloud.githubusercontent.com/assets/5479/12573639/1c9420a6-c3b0-11e5-9fd0-05dd774c74b5.png)

Atom 1.4.1, dartlang 0.5.3, SDK 1.13.1 running on macos.

**Comment by sethladd** [comment] 2016-01-26 06:08
FWIW I was trying to debug, so I set a breakpoint in model.dart, and that's why I was trying to run model_test.dart.

**Comment by devoncarew** [comment] 2016-01-26 17:56
I can repro; we're able to run w/o any breakpoints set, but things fail when you try and set one.

**Comment by devoncarew** [comment] 2016-01-26 17:59
I have to dig into it some more, but it looks like the VM is crashing when I try and set the breakpoint.

**Comment by sethladd** [comment] 2016-01-26 18:07
Thanks for checking it out!

**Comment by devoncarew** [comment] 2016-01-26 18:30
Seth, can you see if this repros in something like the Observatory? It does look like the VM is dying.

**Comment by sethladd** [comment] 2016-01-26 18:35
Try this: `dart --observe --pause-isolates-on-start test/model_test.dart`

That starts for me.

**Comment by devoncarew** [comment] 2016-01-26 18:41
Looks like they ship with minification on. That'll be tough to debug.

@johnmccutchan @turnidge, Seth has found what looks like a crash in the VM when we try and set a breakpoint. Can you see if this repros in the Observatory UI?

**Comment by sethladd** [comment] 2016-01-26 18:46
We're chatting over on the bug in the SDK :) Am trying 1.14. @johnmccutchan was able to confirm the breakpoint works with his (much newer) copy of Observatory.

**Comment by sethladd** [comment] 2016-01-26 18:48
OK, I confirmed it works in Observatory. Grab a 1.14-dev

**Comment by devoncarew** [comment] 2016-01-26 18:51
Yup, I can confirm that it works in observatory. I still suspect a VM issue, as we shouldn't be able to crash it by setting breakpoints.

**Comment by johnmccutchan** [comment] 2016-01-26 18:56
The VM did not crash, Observatory threw an exception.

**Comment by devoncarew** [comment] 2016-01-26 18:58
Do you mean the Observatory UI or the service protocol code?

**Comment by devoncarew** [comment] 2016-01-26 18:59
Here's the traffic to and from Atom and the service protcol:

```
atom.run: Using existing launch config for '/Users/devoncarew/projects/dartdoc/test/model_test.dart'.
atom.run: Launching 'model_test.yaml: cli, test/model_test.dart, cli: {debug: true, checked: true, args: null}'.
process: exec: /Users/devoncarew/homebrew/opt/dart/libexec/bin/dart --enable-vm-service:16230 --pause_isolates_on_start=true --checked test/model_test.dart (cwd=/Users/devoncarew/projects/dartdoc)
atom.observatory: Connected to observatory on ws://localhost:16230/ws.
atom.observatory: ==> {"id":"1","method":"streamListen","params":{"streamId":"_Logging"}}
atom.observatory: ==> {"id":"2","method":"getVersion"}
atom.observatory: ==> {"id":"3","method":"streamListen","params":{"streamId":"Isolate"}}
atom.observatory: ==> {"id":"4","method":"streamListen","params":{"streamId":"Debug"}}
atom.observatory: ==> {"id":"5","method":"getVM"}
atom.observatory: <== {"jsonrpc":"2.0","id":"1","result":{"type":"Success"}}
atom.observatory: <== {"jsonrpc":"2.0","id":"3","result":{"type":"Success"}}
atom.observatory: <== {"jsonrpc":"2.0","id":"4","result":{"type":"Success"}}
atom.observatory: <== {"jsonrpc":"2.0", "result":{"type":"Version","major":3,"minor":0,"_privateMajor":0,"_privateMinor":0},"id":"2"}
atom.observatory: <== {"jsonrpc":"2.0", "result":{"type":"VM","name":"vm","architectureBits":64,"targetCPU":"x64","hostCPU":"Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz","version":"1.14.0-dev.7.2 (Wed Jan 20 10:50:44 2016) on \"macos_x64\"","pid":26635,"startTime":1453834468193,"isolates":[{"type":"@Isolate","fixedId":true,"id":"isolates\/758096563","name":"model_test.dart$main","number":"758096563"}]},"id":"5"}
atom.observatory: Observatory version 3.0.
atom.observatory: Connected to x64 • Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz • Dart 1.14.0-dev.7.2
atom.debugger: resolve /Users/devoncarew/projects/dartdoc/test/model_test.dart ==> [file:///Users/devoncarew/projects/dartdoc/test/model_test.dart]
atom.observatory: ==> {"id":"6","method":"addBreakpointWithScriptUri","params":{"isolateId":"isolates/758096563","scriptUri":"file:///Users/devoncarew/projects/dartdoc/test/model_test.dart","line":19}}
process: exit code: 255 (/Users/devoncarew/homebrew/opt/dart/libexec/bin/dart)
```

**Comment by johnmccutchan** [comment] 2016-01-26 19:08
@devoncarew Okay, that looks like a VM crash.

I just set a breakpoint with:
"scriptUri":"file:///Users/devoncarew/projects/dartdoc/test/model_test.dart"
and 
"line":19

And did not observe a crash.

I'm running Dart VM version: 1.14.0-dev.4.0 (Fri Dec 11 01:51:05 2015) on "linux_x64". I'll try with bleeding edge.

**Comment by johnmccutchan** [comment] 2016-01-26 19:11
I just tried with bleeding edge and didn't see a crash either.

curl localhost:16230/addBreakpointWithScriptUri\?isolateId=isolates/root\&scriptUri=file:///Users/devoncarew/projects/dartdoc/test/model_test.dart\&line=19

**Comment by johnmccutchan** [comment] 2016-01-26 19:12
If you can reproduce the crash, please file a bug against the VM.

**Comment by devoncarew** [comment] 2016-01-26 19:14
`Dart VM version: 1.14.0-dev.7.2 (Wed Jan 20 10:50:44 2016) on "macos_x64"`

Were you trying to set a breakpoint w/ my path (`file:///Users/devoncarew/...`)?

**Comment by johnmccutchan** [comment] 2016-01-26 19:20
I was but it still doesn't crash for me:

$ curl localhost:16230/addBreakpointWithScriptUri\?isolateId=isolates/root\&scriptUri=file:///usr/local/google/home/johnmccutchan/workspace/dartdoc/test/model_test.dart\&line=19
{"jsonrpc":"2.0", "result":{"type":"Breakpoint","fixedId":true,"id":"breakpoints\/1","breakpointNumber":1,"resolved":false,"location":{"type":"UnresolvedSourceLocation","script":{"type":"@Script","fixedId":true,"id":"libraries\/15\/scripts\/file%3A%2F%2F%2Fusr%2Flocal%2Fgoogle%2Fhome%2Fjohnmccutchan%2Fworkspace%2Fdartdoc%2Ftest%2Fmodel_test.dart","uri":"file:\/\/\/usr\/local\/google\/home\/johnmccutchan\/workspace\/dartdoc\/test\/model_test.dart","_kind":"script"},"line":19}},"id":""}

**Comment by sethladd** [comment] 2016-01-27 21:29
I tried to repro it with Dart 1.14-dev.7.2 and with a simple package (no flutter), and the breakpoint toggled. So this works in the most basic simple non-Flutter case.

But I tried with 1.14-dev.7.2 and I could cause the crash.

I'll open a specific SDK issue with repro instructions.

**Comment by devoncarew** [comment] 2016-02-03 03:18
Closing as https://github.com/dart-atom/dartlang/issues/736 is more specific.

**Closed by devoncarew** 2016-02-03 03:18 UTC
Labels: bug, debugger
