### ISSUE TITLE
Add the 'create project...' feature to dart-atom

### ISSUE THREAD

**Issue by AndreaVEH** [dart-atom/dartlang#683] opened 2016-01-09 08:13 UTC
I see there is a 'Create new Flutter project...' option in the Flutter package, but missed in the Dart package. Could we just use atom to create new Dart project template (Web Application, Command line Application, Web Application using Polymer, etc.) as the Dart Editor or other IDEs do.

**Comment by devoncarew** [comment] 2016-01-13 01:00
dupe of #330

**Closed by devoncarew** 2016-01-13 01:00 UTC
Labels: enhancement
