### ISSUE TITLE
After package upgrade, I see two analyzer gears spinning

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#130] opened 2015-07-29 19:43 UTC
Not sure if this is a real issue, but I'm in the settings page, and I just upgraded to 0.3.7 and I saw two analyzer gears spinning.

![screen shot 2015-07-29 at 12 42 44 pm](https://cloud.githubusercontent.com/assets/5479/8967980/6ffe4450-35ef-11e5-945f-ab7632ca3730.png)

**Comment by devoncarew** [comment] 2015-07-29 19:45
Dupe of #85, but thanks for the report and the additional info. Sounds like we're not cleaning up after ourselves on an uninstall.

**Closed by devoncarew** 2015-07-29 19:46 UTC
