### ISSUE TITLE
Provide a way to configure auto-formatting per project

### ISSUE THREAD

**Issue by sethladd** [dart-atom/dartlang#802] opened 2016-02-25 22:43 UTC
Dart project I want auto-formatting.

Flutter projects, not so much.

Can we make this a project-level configuration? Thanks!

Atom 1.5.3, dartlang 0.6.2, SDK 1.14.0 running on macos.

**Comment by devoncarew** [comment] 2016-02-26 00:03
dupe of https://github.com/dart-atom/dartlang/issues/798

**Closed by devoncarew** 2016-02-26 00:03 UTC
Labels: enhancement
