### ISSUE TITLE
Snippets does not work for dart files

### ISSUE THREAD

**Issue by Aetet** [dart-atom/dartlang#915] opened 2016-03-30 05:55 UTC
Snippets does not work for dart files. Is there way to fix them?

**Comment by devoncarew** [comment] 2016-03-30 18:57
It's likely something we're doing in our code completion provider. Thanks for the feedback! closing as a dupe of https://github.com/dart-atom/dartlang/issues/780

**Closed by devoncarew** 2016-03-30 18:57 UTC
