### ISSUE TITLE
outline view clashes with "show references" slidebar.

### ISSUE THREAD

**Issue by skybrian** [dart-atom/dartlang#334] opened 2015-09-17 21:31 UTC
Cosmetic issues (low priority):

The "References" sidebar shows up outside the outline view sidebar, and the tops don't line up. Maybe it should show up inside the outline view sidebar?

Also, the space available for code gets shrinks when the "References" view shows up, because there are two sidebars. So alternatively, perhaps there could be one tabbed sidebar where you can switch between them?

**Comment by devoncarew** [comment] 2016-04-11 03:14
planned now (closing as a dupe of another item)

**Closed by devoncarew** 2016-04-11 03:14 UTC
