### ISSUE TITLE
When I installed dartlang package in atom, and opened my dart project, packages/ symlinks spammed throughout project

### ISSUE THREAD

**Issue by DanielJoyce** [dart-atom/dartlang#114] opened 2015-07-23 18:00 UTC
So when I opened my dart project in atom with dartlang package, I got a whole bunch of packages symlinks added to every directory under the project root

packages
web
web/packages => packages
web/css
web/css/packages => packages

Every single subdirectory had a symlink to packages now.

**Comment by DanielJoyce** [comment] 2015-07-23 18:03
I shoudl says this a polymer dart project. And it appears this links were only created under web/

**Comment by radicaled** [comment] 2015-07-23 23:27
I think this is Dart's current behavior when you run `pub get` -- and you may only be noticing it now because the plugin doesn't explicitly hide the` .packages` directories from you.

**Comment by DanielJoyce** [comment] 2015-07-24 00:01
No, its not .packages, but packages symlinks, no dot in front...

**Comment by DanielJoyce** [comment] 2015-07-24 00:03
Yeah, pub get is doing it...

Pub is spamming packages symlinks into all subfolders of web...

These symlinks are labeled "packages" not ".packages".  Is this a pub regression then?

**Comment by radicaled** [comment] 2015-07-24 01:10
Sorry, I confused myself: at some point in the future there will be a single ".packages" file (or directory? can't remember) that will replace the dozens of "packages" symlinks that `pub get` litters your file tree with.

**Comment by DanielJoyce** [comment] 2015-07-24 03:45
Why does it do it though? Seems to work fine if I remove all of them except for one in web/

**Comment by radicaled** [comment] 2015-07-24 03:48
https://www.dartlang.org/tools/pub/faq.html#what-are-all-the-packages-directories-for

**Comment by devoncarew** [comment] 2015-07-24 10:51
Yup, this is the current behavior for the sdk. In the next release (SDK 1.12), we'll create a `.packages` file _and_ the `packages/` dir symlinks. The plan is that for the release after that one, we will no longer create the symlinks. The transition period will give tools time to update to the new, symlink-less world.

**Comment by devoncarew** [comment] 2015-07-24 10:52
Thanks for the report! I'll close this issue - it's as designed for now.

**Closed by devoncarew** 2015-07-24 10:52 UTC
