### ISSUE TITLE
Highlight occurrences of variables

### ISSUE THREAD

**Issue by tvolkert** [dart-atom/dartlang#547] opened 2015-11-19 21:40 UTC
When the cursor is over a variable, it's very useful to have the IDE highlight all occurrences of that variable.  This applies to static, instance, local, and global variables, as well as method/function/constructor parameters.

Atom 1.0.19, dartlang 0.4.14, SDK 1.13.0-dev.6.0 running on linux.

**Comment by devoncarew** [comment] 2015-12-11 18:53
Dupe of #115

**Closed by devoncarew** 2015-12-11 18:53 UTC
Labels: enhancement
