### ISSUE TITLE
code navigation does not work for files in packages directory

### ISSUE THREAD

**Issue by pstjvn** [dart-atom/dartlang#215] opened 2015-08-13 10:30 UTC
Scenario: install a package with multiple dependencies (I used 'rpc');

If I open a file from a related package directly in atom (using the navigation tree).

Expected result: navigation in that file to work (f3 shortcut).
Actual result: navigation does not work

However if I navigate to a file in the package dir by starting navigation from my own code and going deeper using f3 again it works.

**Comment by devoncarew** [comment] 2015-08-13 17:03
Thanks for the report!

I can confirm the the 2nd case works (user code -> package code, and nav works).

Can you detail the 1st case a bit more? I'm not 100% on how to repro.

**Comment by pstjvn** [comment] 2015-08-13 17:54
Here is exactly how I encountered it.

create new project (stagehand - library)
add dependency on rpc
run pub get
open newly created package directory and navigate to discoveryapis_generate
open any file
try to navigate the symbols using f3 

I was attempting to see how exactly is implemented code generation (out of curiosity).

A workaround was suggested meanwhile - to import ~/.pub cache as a project folder and then those files can be navigated as usual.

**Comment by devoncarew** [comment] 2015-08-14 17:59
OK, thanks, I can repro now.

It looks like if the package is imported by user code then it is navigatable. If it is not imported (but still provisioned by the pubspec) then it is _not_ navigable.

I also note that `dart:` libraries are not navigable, whether they are imported by user code or not.

@bwilkerson @scheglov, is this expected behavior? Is there any way for me to indicate to the user which files will support hyperlink navigation and which ones will not? I am a bit surprised by the dart: behavior.

**Comment by scheglov** [comment] 2015-08-17 17:37
CL for SDK
https://codereview.chromium.org/1289643003

**Comment by scheglov** [comment] 2015-08-17 17:50
Devon, the CL for SDK is landed.
It might also just work with packages now, if you set the file as a priority one.
Please try and let us know it still does not work.

**Comment by devoncarew** [comment] 2015-08-17 18:20
Thanks much! I'll test this on a fresh sdk from the buildbots.

**Comment by devoncarew** [comment] 2015-10-27 08:56
fixed

**Closed by devoncarew** 2015-10-27 08:56 UTC
