### ISSUE TITLE
Show dart docs for autocomplete suggestions

### ISSUE THREAD

**Issue by alechenninger** [dart-atom/dartlang#135] opened 2015-07-30 17:26 UTC
I really like that IntelliJ can do this for example:

![autocomplete_docs](https://cloud.githubusercontent.com/assets/3496559/8990091/0dbd0342-36be-11e5-9540-c4caef01faaa.png)

You can hit F1 to show docs, but you must have typed the entire symbol. Even if you hit tab or enter to choose the autocomplete suggestion, you still have some steps to do until you can view the docs. For example, if it is a method with no params, your cursor is set past the `()`, and F1 does not show docs for the autocompleted method if you leave your cursor here. You have to navigate back to the method manually and hit F1 then.

It would be great if F1 worked for the current selected autocomplete selection, or if docs simply automatically showed up for autocomplete selections.

**Comment by devoncarew** [comment] 2015-07-31 00:35
related to #87

**Comment by pstjvn** [comment] 2015-08-23 11:41
DartEditor behavior in this case was even better imho: the user did not have to do anything to see the doc for the completion while navigating the autocomplete list - it simply was there. Should be configurable maybe?

**Comment by devoncarew** [comment] 2015-12-11 18:51
Dupe of https://github.com/dart-atom/dartlang/issues/87.

**Closed by devoncarew** 2015-12-11 18:51 UTC
